version: "3.3"
services:
  elasticsearch:
    container_name: es-container
    build:
      context: ./docker/elasticsearch/
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=cluster1-node1
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    build:
      context: ./docker/kibana/
    environment:
      ELASTICSEARCH_HOSTS: http://es-container:9200
      SERVER_HOSTS: 0.0.0.0
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  golang:
    build:
      context: ./docker/golang/
    volumes:
      - ./:/app/
    ports:
      - "9000:9000"
    networks:
      - es-net
    depends_on:
      - elasticsearch
    working_dir: "/app"
    privileged: true
    tty: true

networks:
  es-net:
    driver: bridge